# Generated by Django 3.0.6 on 2020-05-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200511_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBySerial',
        ),
    ]
