# Generated by Django 2.2.6 on 2019-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20191021_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='items_pics'),
        ),
    ]
