# Generated by Django 3.0.6 on 2020-05-12 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_itembyserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dailyRentCost',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
